# Generated by Django 5.2.8 on 2025-11-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_add_is_draft_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='poll',
            new_name='polls_poll_created_3f3b19_idx',
            old_name='polls_poll_created_idx',
        ),
        migrations.RenameIndex(
            model_name='poll',
            new_name='polls_poll_is_acti_9835dc_idx',
            old_name='polls_poll_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='poll',
            new_name='polls_poll_is_draf_8aa557_idx',
            old_name='polls_poll_is_draf_idx',
        ),
        migrations.RenameIndex(
            model_name='polloption',
            new_name='polls_pollo_poll_id_0d29f4_idx',
            old_name='polls_pollopt_poll_id_order_idx',
        ),
        migrations.AddField(
            model_name='poll',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='polloption',
            name='text_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='polloption',
            name='text_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='polloption',
            name='text_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='polloption',
            name='text_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
