# Generated by Django 5.2.8 on 2025-11-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_polls_poll_created_idx_polls_poll_created_3f3b19_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='title_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='polloption',
            name='text_sw',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
