# Generated by Django 5.2.8 on 2025-11-18 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_poll_description_sw_poll_title_sw_polloption_text_sw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='polls_categ_slug_ed4993_idx')],
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this poll belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='polls.category'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='polls_tag_slug_e189cb_idx'), models.Index(fields=['name'], name='polls_tag_name_fad238_idx')],
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this poll', related_name='polls', to='polls.tag'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['category'], name='polls_poll_categor_f53d74_idx'),
        ),
    ]
